fda_dbt:
  outputs:
    dev:
      dataset: staging_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/google-creds.json
      location: US
      method: service-account
      priority: interactive
      project: fda-pipeline
      threads: 2
      type: bigquery
  target: dev
